// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function OpenSettingsWindow():Promise<void>;

export function SaveWindowPosition(arg1:number,arg2:number):Promise<void>;
